<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        //\App\Models\User::factory(10)->create();

        $lista = [
            [
                'nome'              => 'Wellington Freitas',
                'email'             => 'wellington.freitas@teste.com',
                'país'              => 'BR',
                'cidade'            => 'São Paulo',
                'estado'            => 'SP',
                'celular'           => '+55 11 98762 4996',
                'data_mantenedor'   => '2023-03-10',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => '1986-04-02',
                'username'          => 'wellington.freitas',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'         => now(),
            ],
            [
                'nome'              => 'Vivianne Stafussi',
                'email'             => 'vivianne.stafussi@teste.com',
                'país'              => 'BR',
                'cidade'            => 'São Paulo',
                'estado'            => 'SP',
                'celular'           => '+55 11 98762 4996',
                'data_mantenedor'   => '2023-03-10',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => '1980-05-02',
                'username'          => 'vivianne.stafussi',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Deborah Stafussi',
                'email'             => 'deborah.stafussi@teste.com',
                'país'              => 'BR',
                'cidade'            => 'São Paulo',
                'estado'            => 'SP',
                'celular'           => '+55 11 98762 4996',
                'data_mantenedor'   => '2023-03-10',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => '1986-04-26',
                'username'          => 'deborah.stafussi',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'         => now(),
            ],
            [
                'nome'              => 'Igreja X',
                'email'             => 'igreja.x@teste.com',
                'país'              => 'BR',
                'cidade'            => 'São Paulo',
                'estado'            => 'SP',
                'celular'           => '+55 11 98762 4996',
                'data_mantenedor'   => '2023-03-12',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'igreja.x',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'         => now(),
            ],
            [
                'nome'              => 'João Silva',
                'email'             => 'joao.silva@teste.com',
                'país'              => 'BR',
                'cidade'            => 'São Paulo',
                'estado'            => 'SP',
                'celular'           => '+55 11 98765 4321',
                'data_mantenedor'   => '2022-01-15',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'joao.silva',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Maria Oliveira',
                'email'             => 'maria.oliveira@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Rio de Janeiro',
                'estado'            => 'RJ',
                'celular'           => '+55 21 99987 6543',
                'data_mantenedor'   => '2021-12-10',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'maria.oliveira',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Carlos Andrade',
                'email'             => 'carlos.andrade@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Belo Horizonte',
                'estado'            => 'MG',
                'celular'           => '+55 31 98877 5566',
                'data_mantenedor'   => '2020-08-25',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'carlos.andrade',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Igreja Luz do Mundo',
                'email'             => 'igreja.luz@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Curitiba',
                'estado'            => 'PR',
                'celular'           => '+55 41 99999 1234',
                'data_mantenedor'   => '2019-05-30',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'igreja.luz',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Laura Mendes',
                'email'             => 'laura.mendes@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Porto Alegre',
                'estado'            => 'RS',
                'celular'           => '+55 51 98765 5678',
                'data_mantenedor'   => '2022-09-15',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'laura.mendes',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Miguel Costa',
                'email'             => 'miguel.costa@teste.com',
                'país'              => 'AR',
                'cidade'            => 'Córdoba',
                'estado'            => 'CD',
                'celular'           => '+54 351 123 4567',
                'data_mantenedor'   => '2023-03-10',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'miguel.costa',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Camila Torres',
                'email'             => 'camila.torres@teste.com',
                'país'              => 'CL',
                'cidade'            => 'Santiago',
                'estado'            => 'ST',
                'celular'           => '+56 2 98765 4321',
                'data_mantenedor'   => '2021-07-05',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'camila.torres',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Pedro Henrique',
                'email'             => 'pedro.henrique@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Fortaleza',
                'estado'            => 'CE',
                'celular'           => '+55 85 99876 1234',
                'data_mantenedor'   => '2020-03-12',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'pedro.henrique',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Ana Paula Almeida',
                'email'             => 'ana.almeida@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Recife',
                'estado'            => 'PE',
                'celular'           => '+55 81 98765 4321',
                'data_mantenedor'   => '2023-01-20',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'ana.almeida',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Rafael Santos',
                'email'             => 'rafael.santos@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Florianópolis',
                'estado'            => 'SC',
                'celular'           => '+55 48 99876 5432',
                'data_mantenedor'   => '2022-11-10',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'rafael.santos',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Igreja Caminho da Fé',
                'email'             => 'igreja.caminho@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Goiânia',
                'estado'            => 'GO',
                'celular'           => '+55 62 99999 1111',
                'data_mantenedor'   => '2020-06-15',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'igreja.caminho',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Lucas Pereira',
                'email'             => 'lucas.pereira@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Manaus',
                'estado'            => 'AM',
                'celular'           => '+55 92 98765 6789',
                'data_mantenedor'   => '2021-08-05',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'lucas.pereira',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Gabriela Moreira',
                'email'             => 'gabriela.moreira@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Salvador',
                'estado'            => 'BA',
                'celular'           => '+55 71 99888 7777',
                'data_mantenedor'   => '2019-02-20',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'gabriela.moreira',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Santiago Rodriguez',
                'email'             => 'santiago.rodriguez@teste.com',
                'país'              => 'AR',
                'cidade'            => 'Buenos Aires',
                'estado'            => 'BA',
                'celular'           => '+54 11 99876 4321',
                'data_mantenedor'   => '2021-03-25',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'santiago.rodriguez',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Sofia Fernández',
                'email'             => 'sofia.fernandez@teste.com',
                'país'              => 'CL',
                'cidade'            => 'Valparaíso',
                'estado'            => 'VA',
                'celular'           => '+56 32 98765 4321',
                'data_mantenedor'   => '2020-10-12',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'sofia.fernandez',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Beatriz Ribeiro',
                'email'             => 'beatriz.ribeiro@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Vitória',
                'estado'            => 'ES',
                'celular'           => '+55 27 99888 9999',
                'data_mantenedor'   => '2023-06-18',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'beatriz.ribeiro',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Felipe Nunes',
                'email'             => 'felipe.nunes@teste.com',
                'país'              => 'BR',
                'cidade'            => 'João Pessoa',
                'estado'            => 'PB',
                'celular'           => '+55 83 99876 5432',
                'data_mantenedor'   => '2022-04-25',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'felipe.nunes',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nome'              => 'Isabella Rocha',
                'email'             => 'isabella.rocha@teste.com',
                'país'              => 'BR',
                'cidade'            => 'Campinas',
                'estado'            => 'SP',
                'celular'           => '+55 19 99999 8888',
                'data_mantenedor'   => '2020-07-08',
                'categoria'         => 1,
                'melhor_dia'        => null,
                'aniversário'       => null,
                'username'          => 'isabella.rocha',
                'password'          => Hash::make('123456'),
                'type_user'         => 1,
                'remember_token'    => Str::random(10),
                'created_at'        => now(),
                'updated_at'        => now(),
            ],

        ];

        foreach($lista as $key => $row){
            DB::table('users')->insert($row);
        }

    }
}
